export default function Reputacao() {
  const countryNames = {
    US: "Estados Unidos",
    CN: "China",
    SG: "Singapura",
    DE: "Alemanha",
    VN: "Vietnã",
    KR: "Coreia do Sul",
    IN: "Índia",
    RU: "Rússia",
    LT: "Lituânia",
    TW: "Taiwan",
    GB: "Reino Unido",
    JP: "Japão",
    IR: "Irã",
    BR: "Brasil",
    AR: "Argentina",
    NL: "Holanda",
    TH: "Tailândia",
    CA: "Canadá",
    PK: "Paquistão",
    ID: "Indonésia",
    ET: "Etiópia",
    FR: "França",
    BG: "Bulgária",
    PA: "Panamá",
    SA: "Arábia Saudita",
    BD: "Bangladesh",
    HK: "Hong Kong",
    MA: "Marrocos",
    EG: "Egito",
    UA: "Ucrânia",
    MX: "México",
    UZ: "Uzbequistão",
    ES: "Espanha",
    AU: "Austrália",
    CO: "Colômbia",
    KZ: "Cazaquistão",
    EC: "Equador",
    BZ: "Belize",
    SN: "Senegal",
    None: "None",
    IE: "Irlanda",
    FI: "Finlândia",
    ZA: "África do Sul",
    IT: "Itália",
    PH: "Filipinas",
    CR: "Costa Rica",
    CH: "Suíça",
  };
  return <></>;
}
