export const ipList = [1, 2, 3, 4, 5, 6, 7, 8, 9];

export const periodList = [
  "jan-mar/2023",
  "abr-jun/2023",
  "jul-set/2023",
  "out-dez/2023",
];

export const featureList = [
  "Clusters",
  "Gráfico de Dispersão",
  "Gráficos de Comportamento",
  "HeatMap de Ocorrência dos IPs nos países",
  "Importâncias para Machine Learning",
  "Mapeamento das features",
  "Reputação por País",
  "Score Average Mobat dos IPs com maior variação",
  "Seleção de Características",
  "Tabela de Acurácia e Tempo de Treinamento dos Modelos",
  "Upload da Tabela dos IPs do período",
];

export const countryList = {
  US: "Estados Unidos",
  CN: "China",
  SG: "Singapura",
  DE: "Alemanha",
  VN: "Vietnã",
  KR: "Coreia do Sul",
  IN: "Índia",
  RU: "Rússia",
  LT: "Lituânia",
  TW: "Taiwan",
  GB: "Reino Unido",
  JP: "Japão",
  IR: "Irã",
  BR: "Brasil",
  AR: "Argentina",
  NL: "Holanda",
  TH: "Tailândia",
  CA: "Canadá",
  PK: "Paquistão",
  ID: "Indonésia",
  ET: "Etiópia",
  FR: "França",
  BG: "Bulgária",
  PA: "Panamá",
  SA: "Arábia Saudita",
  BD: "Bangladesh",
  HK: "Hong Kong",
  MA: "Marrocos",
  EG: "Egito",
  UA: "Ucrânia",
  MX: "México",
  UZ: "Uzbequistão",
  ES: "Espanha",
  AU: "Austrália",
  CO: "Colômbia",
  KZ: "Cazaquistão",
  EC: "Equador",
  BZ: "Belize",
  SN: "Senegal",
  None: "None",
  IE: "Irlanda",
  FI: "Finlândia",
  ZA: "África do Sul",
  IT: "Itália",
  PH: "Filipinas",
  CR: "Costa Rica",
  CH: "Suíça",
};

export const allowedColumns = [
  "abuseipdb_is_whitelisted",
  "abuseipdb_confidence_score",
  "abuseipdb_country_code",
  "abuseipdb_isp",
  "abuseipdb_domain",
  "abuseipdb_total_reports",
  "abuseipdb_num_distinct_users",
  "abuseipdb_last_reported_at",
  "virustotal_reputation",
  "virustotal_regional_internet_registry",
  "virustotal_as_owner",
  "harmless",
  "malicious",
  "suspicious",
  "undetected",
  "IBM_score",
  "IBM_average history Score",
  "IBM_most common score",
  "virustotal_asn",
  "SHODAN_asn",
  "SHODAN_isp",
  "ALIENVAULT_reputation",
  "ALIENVAULT_asn",
  "score_average_Mobat",
];
